### ISSUE TITLE
Geometry Does Not Exist

### ISSUE THREAD

**Issue by Clenera** [koopjs/koop-github#27]
Got the following error when trying to load the URL in the sample-app:

"Failed to create table Github:benbalter/dc-wifi-social/bars:0 error:error: type \"geometry\" does not exist"

I submitted a ticket in the sample-app and they said it may have something to do with this provider.

**Comment by jgravois** [comment]
thanks @clenara.  we'll look into it.

**Comment by ngoldman** [comment]
@jgravois I was able to get geojson from `/github/benbalter/dc-wifi-social/bars` using the edge version of koop-github (PR here: https://github.com/koopjs/koop-github/pull/28). Haven't had time to try to reproduce with the older version yet.

**Comment by jgravois** [comment]
I reproed the bug report on the 25th

**Comment by jgravois** [comment]
i can't repo anymore.  see my comment [here](https://github.com/koopjs/koop-sample-app/issues/29#issuecomment-148450137) for a tad more info.

**Comment by ngoldman** [comment]
Marking this as resolved.
