### ISSUE TITLE
we should remove the config folder from provider repositories entirely (i think)

### ISSUE THREAD

**Issue by jgravois** [koopjs/koop-github#9]
my own testing seems to indicate that configuration of caching is inherited from koop/koop-server.  if it would be appropriate to remove configuration folder in individual provider repos, let me know and i will submit a PR.

**Comment by chelm** [comment]
ahh yes now I see this. So the these configs are for testing purposes. Should probably just move them into the test dir.

**Comment by jgravois** [comment]
ahhh... now it makes more sense.  im happy to submit PRs which move the config folders for individual providers into their corresponding test directories but i'll try and get the tests running first to make sure nothing else needs changed.

i had trouble running koop-server tests earlier, but its worth another shot.

**Comment by ngoldman** [comment]
+1
